### ISSUE TITLE
Build spring modules against spring v3

### ISSUE THREAD

**Issue by ianhomer** [astubbs/spring-modules#12]
Spring modules is currently built against 2.5.6 and does not support Spring v3.

Any chance the spring version that spring modules depends on could be upgraded?

I'll be happy to take a look at doing this if such a patch would be considered.

**Comment by astubbs** [comment]
Absolutely - please take a look at the google group and comment. there's another person who's also interested in this work.

**Comment by ianhomer** [comment]
For reference - thread on subject @ http://groups.google.com/group/spring-modules-fork/browse_thread/thread/1cb4e69359063216

**Comment by rossajmcd** [comment]
Make that another who is interested :-)

**Comment by astubbs** [comment]
lol @ianhomer
